# AI-assisted experimental code; full human and mathematical review is not established.
"""
Gröbner bases over exact coefficients.

Core: Buchberger's algorithm, multivariate polynomial division.
Derived: normal forms, ideal membership, elimination, relations among generators.

All functions take an explicit monomial ordering (default: grlex).
"""

from __future__ import annotations

from fractions import Fraction

from . import poly
from .poly import Poly


# -- Multivariate division (reduction) --

def reduce(f: Poly, G: list[Poly], order=poly.grlex) -> Poly:
    """Reduce f modulo G by repeated leading-term cancellation.

    Returns the remainder (normal form if G is a Gröbner basis).
    """
    r: Poly = {}
    p = dict(f)
    while p:
        reduced = False
        for g in G:
            if not g:
                continue
            lm_g = poly.leading_monomial(g, order)
            lc_g = poly.leading_coefficient(g, order)
            # find any term in p divisible by LT(g)
            for alpha in sorted(p.keys(), key=order, reverse=True):
                if poly.mono_divides(lm_g, alpha):
                    quot_mono = poly.mono_div(alpha, lm_g)
                    quot_coeff = p[alpha] / lc_g
                    # subtract quot * g from p
                    shift = poly.mul(poly.mono(quot_mono, quot_coeff), g)
                    p = poly.sub(p, shift)
                    reduced = True
                    break
            if reduced:
                break
        if not reduced:
            # move the leading term of p to the remainder
            if p:
                lm_p = poly.leading_monomial(p, order)
                lc_p = p[lm_p]
                r = poly.add(r, poly.mono(lm_p, lc_p))
                del p[lm_p]
    return r


def s_poly(f: Poly, g: Poly, order=poly.grlex) -> Poly:
    """S-polynomial of f and g."""
    lm_f = poly.leading_monomial(f, order)
    lm_g = poly.leading_monomial(g, order)
    lc_f = poly.leading_coefficient(f, order)
    lc_g = poly.leading_coefficient(g, order)
    gamma = poly.mono_lcm(lm_f, lm_g)
    t_f = poly.mono(poly.mono_div(gamma, lm_f), Fraction(1) / lc_f)
    t_g = poly.mono(poly.mono_div(gamma, lm_g), Fraction(1) / lc_g)
    return poly.sub(poly.mul(t_f, f), poly.mul(t_g, g))


# -- Buchberger's algorithm --

def buchberger(F: list[Poly], order=poly.grlex) -> list[Poly]:
    """Compute a Gröbner basis for the ideal generated by F.

    Returns a reduced Gröbner basis (monic, inter-reduced).
    """
    G = [g for g in F if g]
    if not G:
        return []

    pairs = [(i, j) for i in range(len(G)) for j in range(i + 1, len(G))]
    while pairs:
        i, j = pairs.pop(0)
        sp = s_poly(G[i], G[j], order)
        r = reduce(sp, G, order)
        if r:
            k = len(G)
            pairs.extend((m, k) for m in range(k))
            G.append(r)

    return _reduce_basis(G, order)


def _reduce_basis(G: list[Poly], order) -> list[Poly]:
    """Inter-reduce and make monic."""
    # make monic
    G = [poly.scale(Fraction(1) / poly.leading_coefficient(g, order), g) for g in G]

    # remove redundant elements
    minimal = []
    for i, g in enumerate(G):
        lm = poly.leading_monomial(g, order)
        if not any(
            poly.mono_divides(poly.leading_monomial(h, order), lm)
            for j, h in enumerate(G)
            if j != i and h in minimal
        ):
            minimal.append(g)

    # inter-reduce: reduce each element by the others
    reduced = []
    for i, g in enumerate(minimal):
        others = minimal[:i] + minimal[i + 1:]
        r = reduce(g, others, order)
        if r:
            # re-normalize
            r = poly.scale(Fraction(1) / poly.leading_coefficient(r, order), r)
            reduced.append(r)
    return reduced


# -- Derived operations --

def normal_form(f: Poly, basis: list[Poly], order=poly.grlex) -> Poly:
    """Normal form of f with respect to a Gröbner basis.

    The remainder is the unique canonical representative of f mod I.
    """
    return reduce(f, basis, order)


def in_ideal(f: Poly, basis: list[Poly], order=poly.grlex) -> bool:
    """Test whether f belongs to the ideal generated by basis.

    Requires basis to be a Gröbner basis.
    """
    return not normal_form(f, basis, order)


def ideal_intersection(F: list[Poly], G: list[Poly], n_vars: int) -> list[Poly]:
    """Intersection of ideals I = (F) and J = (G) in k[x_0, ..., x_{n-1}].

    Introduces a new variable t (index 0) and forms the ideal
    (t*f_1, ..., t*f_r, (1-t)*g_1, ..., (1-t)*g_s) in k[t, x_0, ..., x_{n-1}].
    Eliminates t; the surviving polynomials generate I ∩ J.
    """
    # Embed into k[t, x_0, ..., x_{n-1}]: prepend one variable
    t_var = poly.var(0, n_vars + 1)                    # t
    one_minus_t = poly.sub(poly.const(1, n_vars + 1), t_var)  # 1 - t

    def embed(f: Poly) -> Poly:
        """Shift all variables up by 1 to make room for t."""
        return {(0,) + alpha: c for alpha, c in f.items()}

    gens = []
    for f in F:
        gens.append(poly.mul(t_var, embed(f)))
    for g in G:
        gens.append(poly.mul(one_minus_t, embed(g)))

    # Eliminate t (variable 0), then strip the leading 0 from exponent tuples
    elim = eliminate(gens, k=1, n_vars=n_vars + 1)
    return [{alpha[1:]: c for alpha, c in g.items()} for g in elim]


def eliminate(generators: list[Poly], k: int, n_vars: int) -> list[Poly]:
    """Elimination of the first k variables.

    Computes a Gröbner basis with an elimination ordering that pushes
    x_0, ..., x_{k-1} to the top, then returns only the polynomials
    that live in k[x_k, ..., x_{n-1}].
    """
    order = poly.elimination_order(k)
    gb = buchberger(generators, order)
    return [g for g in gb if _involves_only(g, k, n_vars)]


def _max_var(f: Poly) -> int:
    """Highest variable index with nonzero exponent in f, or -1."""
    m = -1
    for alpha in f:
        for i, e in enumerate(alpha):
            if e > 0 and i > m:
                m = i
    return m


def _involves_only(f: Poly, start: int, n_vars: int) -> bool:
    """True if f only involves variables x_start, ..., x_{n_vars-1}."""
    for alpha in f:
        for i in range(start):
            if alpha[i] != 0:
                return False
    return True


def compute_relations(generators: list[Poly], n_vars: int,
                      order=poly.grlex) -> list[Poly]:
    """Compute relations among polynomial generators.

    Given generators g_1, ..., g_s in k[x_0, ..., x_{n-1}], introduce
    new variables y_0, ..., y_{s-1} and compute the kernel of the map
    k[y_0, ..., y_{s-1}] -> k[x_0, ..., x_{n-1}] sending y_i -> g_i.

    This kernel is the ideal of relations. We find it by elimination:
    form the ideal <y_0 - g_0, ..., y_{s-1} - g_{s-1}> in k[x, y]
    and eliminate x_0, ..., x_{n-1}.
    """
    s = len(generators)
    total_vars = n_vars + s

    # embed each g_i into k[x_0,...,x_{n-1}, y_0,...,y_{s-1}]
    elim_gens = []
    for i, g in enumerate(generators):
        # y_i
        y_alpha = (0,) * n_vars + tuple(1 if j == i else 0 for j in range(s))
        yi = poly.mono(y_alpha)
        # embed g into the larger ring
        g_emb: Poly = {}
        for alpha, c in g.items():
            new_alpha = alpha + (0,) * s
            g_emb[new_alpha] = c
        elim_gens.append(poly.sub(yi, g_emb))

    # eliminate x_0, ..., x_{n-1}
    elim_order = poly.elimination_order(n_vars)
    gb = buchberger(elim_gens, elim_order)

    # keep only polynomials in k[y_0, ..., y_{s-1}]
    relations = [g for g in gb if _involves_only(g, n_vars, total_vars)]
    return [{alpha[n_vars:]: c for alpha, c in g.items()} for g in relations]


# -- Hilbert function from a Gröbner basis --

def hilbert_function(basis: list[Poly], n_vars: int, max_d: int,
                     order=poly.grlex) -> list[int]:
    """Hilbert function of k[x]/I from degree 0 to max_d.

    Counts monomials of each degree not divisible by any leading monomial
    of the Gröbner basis. Requires basis to be a Gröbner basis.
    """
    leading_monomials = [poly.leading_monomial(g, order) for g in basis if g]
    result = []
    for d in range(max_d + 1):
        count = 0
        for alpha in poly.monomials_of_degree(n_vars, d):
            if not any(poly.mono_divides(lm, alpha) for lm in leading_monomials):
                count += 1
        result.append(count)
    return result


# -- Nullstellensatz test --

def has_common_root(basis: list[Poly], order=poly.grlex) -> bool:
    """Test whether the variety V(I) is nonempty.

    Computes a Gröbner basis and checks whether 1 is NOT in the ideal.
    By the Nullstellensatz, V(I) = {} iff I = k[x], iff GB = {1}.
    """
    gb = buchberger(basis, order)
    # If the GB contains a nonzero constant, the ideal is all of k[x]
    for g in gb:
        if all(e == 0 for e in poly.leading_monomial(g, order)):
            return False  # 1 ∈ I, so no common root
    return True


# -- Syzygies --

def compute_syzygies(generators: list[Poly], n_vars: int,
                     order=poly.grlex) -> list[Poly]:
    """Return pairwise Koszul syzygies, encoded in x and formal e variables.

    For each i<j, return f_j*e_i-f_i*e_j. Substituting e_i=f_i makes each
    polynomial zero. This family need not generate the whole syzygy module;
    computing that module requires a module-Groebner algorithm. The final
    len(generators) coordinates are the formal e variables.
    """
    size = len(generators)
    result = []
    for i in range(size):
        for j in range(i + 1, size):
            left = {alpha + tuple(int(k == i) for k in range(size)): c
                    for alpha, c in generators[j].items()}
            right = {alpha + tuple(int(k == j) for k in range(size)): c
                     for alpha, c in generators[i].items()}
            syzygy = poly.sub(left, right)
            if syzygy:
                result.append(syzygy)
    return result
